config/routes.rb
Rails.application.routes.draw do
  resources :asistents

  resources :akces

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/akce.rb
class Akce < ActiveRecord::Base
  belongs_to :typ_akce
  has_many :asistent_akces
end

app/models/asistent.rb
class Asistent < ActiveRecord::Base
  has_many :asistent_akces
  has_many :asistent_attr_dates
  has_many :asistent_attr_bools
  has_many :asistent_attr_texts
end

app/models/asistent_akce.rb
class AsistentAkce < ActiveRecord::Base
  belongs_to :akce
  belongs_to :asistent
end

app/models/asistent_attr_bool.rb
class AsistentAttrBool < ActiveRecord::Base
  belongs_to :attr_bool
  belongs_to :asistent
end

app/models/asistent_attr_date.rb
class AsistentAttrDate < ActiveRecord::Base
  belongs_to :asistent
  belongs_to :attr_date
end

app/models/asistent_attr_text.rb
class AsistentAttrText < ActiveRecord::Base
  belongs_to :attr_text
  belongs_to :asistent
end

app/models/attr_bool.rb
class AttrBool < ActiveRecord::Base
  has_many :asistent_attr_bools
end

app/models/attr_date.rb
class AttrDate < ActiveRecord::Base
  has_many :asistent_attr_dates
end

app/models/attr_text.rb
class AttrText < ActiveRecord::Base
  has_many :asistent_attr_texts
end

app/models/typ_akce.rb
class TypAkce < ActiveRecord::Base
  has_many :akces
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/akces_controller.rb
class AkcesController < ApplicationController
  before_action :set_akce, only: [:show, :edit, :update, :destroy]

  # GET /akces
  # GET /akces.json
  def index
    @akces = Akce.all
  end

  # GET /akces/1
  # GET /akces/1.json
  def show
  end

  # GET /akces/new
  def new
    @akce = Akce.new
  end

  # GET /akces/1/edit
  def edit
  end

  # POST /akces
  # POST /akces.json
  def create
    @akce = Akce.new(akce_params)

    respond_to do |format|
      if @akce.save
        format.html { redirect_to @akce, notice: 'Akce was successfully created.' }
        format.json { render :show, status: :created, location: @akce }
      else
        format.html { render :new }
        format.json { render json: @akce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /akces/1
  # PATCH/PUT /akces/1.json
  def update
    respond_to do |format|
      if @akce.update(akce_params)
        format.html { redirect_to @akce, notice: 'Akce was successfully updated.' }
        format.json { render :show, status: :ok, location: @akce }
      else
        format.html { render :edit }
        format.json { render json: @akce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akces/1
  # DELETE /akces/1.json
  def destroy
    @akce.destroy
    respond_to do |format|
      format.html { redirect_to akces_url, notice: 'Akce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_akce
      @akce = Akce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def akce_params
      params.require(:akce).permit(:termin_od, :termin_do, :nazev, :typ_akce_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/asistents_controller.rb
class AsistentsController < ApplicationController
  before_action :set_asistent, only: [:show, :edit, :update, :destroy]

  # GET /asistents
  # GET /asistents.json
  def index
    @asistents = Asistent.all
  end

  # GET /asistents/1
  # GET /asistents/1.json
  def show
  end

  # GET /asistents/new
  def new
    @asistent = Asistent.new
  end

  # GET /asistents/1/edit
  def edit
  end

  # POST /asistents
  # POST /asistents.json
  def create
    @asistent = Asistent.new(asistent_params)

    respond_to do |format|
      if @asistent.save
        format.html { redirect_to @asistent, notice: 'Asistent was successfully created.' }
        format.json { render :show, status: :created, location: @asistent }
      else
        format.html { render :new }
        format.json { render json: @asistent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asistents/1
  # PATCH/PUT /asistents/1.json
  def update
    respond_to do |format|
      if @asistent.update(asistent_params)
        format.html { redirect_to @asistent, notice: 'Asistent was successfully updated.' }
        format.json { render :show, status: :ok, location: @asistent }
      else
        format.html { render :edit }
        format.json { render json: @asistent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asistents/1
  # DELETE /asistents/1.json
  def destroy
    @asistent.destroy
    respond_to do |format|
      format.html { redirect_to asistents_url, notice: 'Asistent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asistent
      @asistent = Asistent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asistent_params
      params.require(:asistent).permit(:jmeno, :email, :telefon, :poznamka, :ma_mlcenlivost)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/akces_helper.rb
module AkcesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asistents_helper.rb
module AsistentsHelper
end

app/views/akces/_form.html.erb
<%= simple_form_for(@akce) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :termin_od %>
    <%= f.input :termin_do %>
    <%= f.input :nazev %>
    <%= f.association :typ_akce %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/akces/edit.html.erb
<h1>Editing akce</h1>

<%= render 'form' %>

<%= link_to 'Show', @akce %> |
<%= link_to 'Back', akces_path %>

app/views/akces/index.html.erb
<h1>Listing akces</h1>

<table>
  <thead>
    <tr>
      <th>Termin od</th>
      <th>Termin do</th>
      <th>Nazev</th>
      <th>Typ akce</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @akces.each do |akce| %>
      <tr>
        <td><%= akce.termin_od %></td>
        <td><%= akce.termin_do %></td>
        <td><%= akce.nazev %></td>
        <td><%= akce.typ_akce %></td>
        <td><%= link_to 'Show', akce %></td>
        <td><%= link_to 'Edit', edit_akce_path(akce) %></td>
        <td><%= link_to 'Destroy', akce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Akce', new_akce_path %>

app/views/akces/new.html.erb
<h1>New akce</h1>

<%= render 'form' %>

<%= link_to 'Back', akces_path %>

app/views/akces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Termin od:</strong>
  <%= @akce.termin_od %>
</p>

<p>
  <strong>Termin do:</strong>
  <%= @akce.termin_do %>
</p>

<p>
  <strong>Nazev:</strong>
  <%= @akce.nazev %>
</p>

<p>
  <strong>Typ akce:</strong>
  <%= @akce.typ_akce %>
</p>

<%= link_to 'Edit', edit_akce_path(@akce) %> |
<%= link_to 'Back', akces_path %>

app/views/asistents/_form.html.erb
<%= simple_form_for(@asistent) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :jmeno %>
    <%= f.input :email %>
    <%= f.input :telefon %>
    <%= f.input :poznamka %>
    <%= f.input :ma_mlcenlivost %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/asistents/edit.html.erb
<h1>Editing asistent</h1>

<%= render 'form' %>

<%= link_to 'Show', @asistent %> |
<%= link_to 'Back', asistents_path %>

app/views/asistents/index.html.erb
<h1>Listing asistents</h1>

<table>
  <thead>
    <tr>
      <th>Jmeno</th>
      <th>Email</th>
      <th>Telefon</th>
      <th>Poznamka</th>
      <th>Ma mlcenlivost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asistents.each do |asistent| %>
      <tr>
        <td><%= asistent.jmeno %></td>
        <td><%= asistent.email %></td>
        <td><%= asistent.telefon %></td>
        <td><%= asistent.poznamka %></td>
        <td><%= asistent.ma_mlcenlivost %></td>
        <td><%= link_to 'Show', asistent %></td>
        <td><%= link_to 'Edit', edit_asistent_path(asistent) %></td>
        <td><%= link_to 'Destroy', asistent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asistent', new_asistent_path %>

app/views/asistents/new.html.erb
<h1>New asistent</h1>

<%= render 'form' %>

<%= link_to 'Back', asistents_path %>

app/views/asistents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jmeno:</strong>
  <%= @asistent.jmeno %>
</p>

<p>
  <strong>Email:</strong>
  <%= @asistent.email %>
</p>

<p>
  <strong>Telefon:</strong>
  <%= @asistent.telefon %>
</p>

<p>
  <strong>Poznamka:</strong>
  <%= @asistent.poznamka %>
</p>

<p>
  <strong>Ma mlcenlivost:</strong>
  <%= @asistent.ma_mlcenlivost %>
</p>

<%= link_to 'Edit', edit_asistent_path(@asistent) %> |
<%= link_to 'Back', asistents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RamusAsistenti</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>